import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Medical Store",
  description: "Generated by Firman Perdana",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* <!-- Font Awesome Icons --> */}
        <Script src="https://kit.fontawesome.com/42d5adcbca.js"></Script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
